name: Preview Environment Deploy

on:
  pull_request:
    branches:
      - main

concurrency:
  # more info here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  
jobs:
  deploy-preview:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Context
      uses: okteto/context@latest
      with:
        url: ${{ secrets.OKTETO_CONTEXT }}
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy Preview Environment
      uses: okteto/deploy-preview@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: url-shortener-pr-${{ github.event.number }}
        timeout: 15m

    - name: Run Tests
      uses: okteto/test@latest
      with:
        name: url-shortener-pr-${{ github.event.number }}
